### ISSUE TITLE
NetCoreServer sometimes does not get full requests

### ISSUE THREAD

**Issue by sp00ktober** [sp00ktober/WorldsAdriftReborn#1]
NetCoreServer sometimes does not get the full request send by the game and thus does not send a response. The game does not proceed in that case and it needs to be restarted.

`HttpSession.OnReceived()` is called but `HttpSession.OnReceivedRequest()` is not.

Find out why this happens :)

**Comment by kroney2** [comment]
https://github.com/sp00ktober/WorldsAdriftReborn/pull/23
